// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/courses/{id}/comments": {
            "get": {
                "tags": [
                    "评论"
                ],
                "summary": "获取课程评论",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "课程ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.CommentView"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/student/auth/login": {
            "post": {
                "description": "学生登录获取token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "学生认证"
                ],
                "summary": "学生登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/student/auth/register": {
            "post": {
                "description": "学生注册账号，需要选择校区",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "学生认证"
                ],
                "summary": "学生注册",
                "parameters": [
                    {
                        "description": "注册信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/student/branches": {
            "get": {
                "description": "获取所有可选的校区列表，用于注册时选择",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "学生认证"
                ],
                "summary": "获取校区列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Branches"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/student/courses": {
            "get": {
                "description": "获取所有可用课程列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "学生课程"
                ],
                "summary": "获取课程列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/student/courses/{id}": {
            "get": {
                "description": "获取课程详细信息，包含章节和课程",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "学生课程"
                ],
                "summary": "获取课程详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "课程ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.CourseInfo"
                        }
                    }
                }
            }
        },
        "/api/v1/student/courses/{id}/comments": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "学生评论"
                ],
                "summary": "学生发表评论",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "课程ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "评论",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.AddCommentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Comments"
                        }
                    }
                }
            }
        },
        "/api/v1/student/courses/{id}/enroll": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "学生学习"
                ],
                "summary": "学生报名课程",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "课程ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Learning"
                        }
                    }
                }
            }
        },
        "/api/v1/student/courses/{id}/progress": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "学生学习"
                ],
                "summary": "获取学习进度",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "课程ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Learning"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "学生学习"
                ],
                "summary": "更新学习进度",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "课程ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "学习进度",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UpdateProgressRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Learning"
                        }
                    }
                }
            }
        },
        "/api/v1/student/courses/{id}/tasks": {
            "get": {
                "description": "获取指定课程的所有任务列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "学生任务"
                ],
                "summary": "获取课程的所有任务",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "课程ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.TaskInfo"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/student/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前登录学生的个人信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "学生认证"
                ],
                "summary": "获取个人信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.UserInfo"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/student/tasks/{id}": {
            "get": {
                "description": "获取任务详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "学生任务"
                ],
                "summary": "获取任务详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "任务ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.TaskInfo"
                        }
                    }
                }
            }
        },
        "/api/v1/student/tasks/{id}/answers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前学生在指定任务下的作业",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "学生任务"
                ],
                "summary": "学生查询作业",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "任务ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Answers"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "学生上传作业文本或图片",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "学生任务"
                ],
                "summary": "学生提交作业",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "任务ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "作业文本内容",
                        "name": "answer_content",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "作业类型(text/image_url)，默认为text",
                        "name": "type",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "作业图片文件",
                        "name": "file",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Answers"
                        }
                    }
                }
            }
        },
        "/api/v1/teacher/answers/{id}/grade": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据 answer_id 评分（限本分支教师）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "教师任务管理"
                ],
                "summary": "教师评分",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "作业ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "评分信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.GradeAnswerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Answers"
                        }
                    }
                }
            }
        },
        "/api/v1/teacher/auth/login": {
            "post": {
                "description": "教师登录获取token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "教师认证"
                ],
                "summary": "教师登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/teacher/courses": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前教师创建的所有课程",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "教师课程管理"
                ],
                "summary": "获取我的课程列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "教师创建新课程",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "教师课程管理"
                ],
                "summary": "创建课程",
                "parameters": [
                    {
                        "description": "课程信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CreateCourseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Courses"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/teacher/courses/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取课程详细信息，包含章节和课程",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "教师课程管理"
                ],
                "summary": "获取课程详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "课程ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.CourseInfo"
                        }
                    }
                }
            }
        },
        "/api/v1/teacher/courses/{id}/chapters": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "为课程创建新章节",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "教师课程管理"
                ],
                "summary": "创建章节",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "课程ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "章节信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CreateChapterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Chapters"
                        }
                    }
                }
            }
        },
        "/api/v1/teacher/courses/{id}/chapters/{chapter_id}/lessons": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "为章节创建新课程，可以上传视频文件",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "教师课程管理"
                ],
                "summary": "创建课程",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "课程ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "章节ID",
                        "name": "chapter_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "课程标题",
                        "name": "lesson_title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "video",
                        "description": "课程类型",
                        "name": "lesson_type",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "课程顺序",
                        "name": "lesson_order",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "视频文件",
                        "name": "video_file",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Lessons"
                        }
                    }
                }
            }
        },
        "/api/v1/teacher/courses/{id}/learning": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "教师学习"
                ],
                "summary": "查看课程学习进度",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "课程ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.LearningProgressView"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/teacher/courses/{id}/tasks": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取指定课程的所有任务列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "教师任务管理"
                ],
                "summary": "获取课程的所有任务",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "课程ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.TaskInfo"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/teacher/lessons/{id}/tasks": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "为课程创建新任务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "教师任务管理"
                ],
                "summary": "创建任务",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "课程ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "任务信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CreateTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Tasks"
                        }
                    }
                }
            }
        },
        "/api/v1/teacher/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前登录教师的个人信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "教师认证"
                ],
                "summary": "获取个人信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.UserInfo"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/teacher/tasks/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取任务详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "教师任务管理"
                ],
                "summary": "获取任务详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "任务ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.TaskInfo"
                        }
                    }
                }
            }
        },
        "/api/v1/teacher/tasks/{id}/answers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "教师获取当前任务下的所有作业（仅自己的分支）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "教师任务管理"
                ],
                "summary": "查看作业",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "任务ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Answers"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Answers": {
            "type": "object",
            "properties": {
                "answer_content": {
                    "description": "文本内容或图片URL",
                    "type": "string"
                },
                "answer_id": {
                    "type": "integer"
                },
                "branch": {
                    "description": "关联关系",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Branches"
                        }
                    ]
                },
                "branch_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "graded_by": {
                    "description": "批改老师的ID",
                    "type": "integer"
                },
                "grader": {
                    "description": "批改老师",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Users"
                        }
                    ]
                },
                "is_graded": {
                    "type": "boolean"
                },
                "score": {
                    "type": "integer"
                },
                "submitted_at": {
                    "type": "string"
                },
                "task_id": {
                    "type": "integer"
                },
                "type": {
                    "description": "text, image_url",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/models.Users"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.Branches": {
            "type": "object",
            "properties": {
                "branch_id": {
                    "type": "integer"
                },
                "branch_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Chapters": {
            "type": "object",
            "properties": {
                "chapter_id": {
                    "type": "integer"
                },
                "chapter_order": {
                    "type": "integer"
                },
                "chapter_title": {
                    "type": "string"
                },
                "course": {
                    "description": "关联关系",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Courses"
                        }
                    ]
                },
                "course_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "lessons": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Lessons"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Comments": {
            "type": "object",
            "properties": {
                "branch": {
                    "description": "关联关系",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Branches"
                        }
                    ]
                },
                "branch_id": {
                    "type": "integer"
                },
                "comment_content": {
                    "type": "string"
                },
                "comment_id": {
                    "type": "integer"
                },
                "course_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "parent_comment": {
                    "$ref": "#/definitions/models.Comments"
                },
                "parent_comment_id": {
                    "description": "回复的评论ID",
                    "type": "integer"
                },
                "replies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Comments"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/models.Users"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.Courses": {
            "type": "object",
            "properties": {
                "chapters": {
                    "description": "关联关系（这些关联在分支节点查询时需要从中央服务器获取）",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Chapters"
                    }
                },
                "course_id": {
                    "type": "integer"
                },
                "course_title": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "instructor_id": {
                    "type": "integer"
                },
                "lessons": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Lessons"
                    }
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "description": "active, archived",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Learning": {
            "type": "object",
            "properties": {
                "completed_at": {
                    "type": "string"
                },
                "course_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "learning_id": {
                    "type": "integer"
                },
                "progress_percentage": {
                    "type": "integer"
                },
                "status": {
                    "description": "enrolled, in_progress, completed",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user": {
                    "description": "关联关系",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Users"
                        }
                    ]
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.Lessons": {
            "type": "object",
            "properties": {
                "chapter": {
                    "$ref": "#/definitions/models.Chapters"
                },
                "chapter_id": {
                    "type": "integer"
                },
                "content_url": {
                    "description": "OSS视频链接",
                    "type": "string"
                },
                "course": {
                    "description": "关联关系",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Courses"
                        }
                    ]
                },
                "course_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "lesson_id": {
                    "type": "integer"
                },
                "lesson_order": {
                    "type": "integer"
                },
                "lesson_title": {
                    "type": "string"
                },
                "lesson_type": {
                    "description": "video, text, quiz",
                    "type": "string"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tasks"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Tasks": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "lesson": {
                    "description": "关联关系",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Lessons"
                        }
                    ]
                },
                "lesson_id": {
                    "type": "integer"
                },
                "max_score": {
                    "type": "integer"
                },
                "task_id": {
                    "type": "integer"
                },
                "task_title": {
                    "type": "string"
                },
                "task_type": {
                    "description": "essay, quiz, upload",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Users": {
            "type": "object",
            "properties": {
                "branch": {
                    "description": "关联关系",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Branches"
                        }
                    ]
                },
                "branch_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "role": {
                    "description": "student, teacher",
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "service.AddCommentRequest": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "parent_comment_id": {
                    "type": "integer"
                }
            }
        },
        "service.ChapterInfo": {
            "type": "object",
            "properties": {
                "chapter_id": {
                    "type": "integer"
                },
                "chapter_order": {
                    "type": "integer"
                },
                "chapter_title": {
                    "type": "string"
                },
                "course_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "lessons": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.LessonInfo"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "service.CommentView": {
            "type": "object",
            "properties": {
                "branch_id": {
                    "type": "integer"
                },
                "comment_content": {
                    "type": "string"
                },
                "comment_id": {
                    "type": "integer"
                },
                "course_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "parent_comment_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "service.CourseInfo": {
            "type": "object",
            "properties": {
                "chapters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.ChapterInfo"
                    }
                },
                "course_id": {
                    "type": "integer"
                },
                "course_title": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "instructor_branch_id": {
                    "type": "integer"
                },
                "instructor_branch_user_id": {
                    "type": "integer"
                },
                "instructor_id": {
                    "type": "integer"
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "service.CreateChapterRequest": {
            "type": "object",
            "required": [
                "chapter_title"
            ],
            "properties": {
                "chapter_order": {
                    "type": "integer"
                },
                "chapter_title": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            }
        },
        "service.CreateCourseRequest": {
            "type": "object",
            "required": [
                "course_title"
            ],
            "properties": {
                "course_title": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "service.CreateTaskRequest": {
            "type": "object",
            "required": [
                "task_title"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "max_score": {
                    "type": "integer"
                },
                "task_title": {
                    "type": "string"
                },
                "task_type": {
                    "description": "essay, quiz, upload",
                    "type": "string"
                }
            }
        },
        "service.GradeAnswerRequest": {
            "type": "object",
            "required": [
                "score"
            ],
            "properties": {
                "score": {
                    "type": "integer"
                }
            }
        },
        "service.LearningProgressView": {
            "type": "object",
            "properties": {
                "branch_id": {
                    "type": "integer"
                },
                "completed_at": {
                    "type": "string"
                },
                "course_id": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "progress_percentage": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "service.LessonInfo": {
            "type": "object",
            "properties": {
                "chapter_id": {
                    "type": "integer"
                },
                "content_url": {
                    "type": "string"
                },
                "course_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "lesson_id": {
                    "type": "integer"
                },
                "lesson_order": {
                    "type": "integer"
                },
                "lesson_title": {
                    "type": "string"
                },
                "lesson_type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "service.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "service.LoginResponse": {
            "type": "object",
            "properties": {
                "branch_id": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "service.RegisterRequest": {
            "type": "object",
            "required": [
                "branch_id",
                "email",
                "password",
                "username"
            ],
            "properties": {
                "branch_id": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "service.RegisterResponse": {
            "type": "object",
            "properties": {
                "branch_id": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "service.TaskInfo": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "lesson_id": {
                    "type": "integer"
                },
                "max_score": {
                    "type": "integer"
                },
                "task_id": {
                    "type": "integer"
                },
                "task_title": {
                    "type": "string"
                },
                "task_type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "service.UpdateProgressRequest": {
            "type": "object",
            "properties": {
                "progress_percentage": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "service.UserInfo": {
            "type": "object",
            "properties": {
                "branch_id": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT Authorization header using the Bearer scheme. Example: \"Bearer {token}\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "分布式在线学习平台 API",
	Description:      "这是一个分布式在线学习平台的API文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
